export const DEFAULT_LOGO_SRC = 'assets/breezing-logo-web.png';
export const BASE_DOCUMENT_WIDTH = 1240;
export const BASE_DOCUMENT_HEIGHT = 1754;
export const PREVIEW_DOCUMENT_WIDTH = 794;
export const STORAGE_KEY = 'breezing-studio-manager-layout';
export const ACCESS_STORAGE_KEY = 'breezing-studio-manager-access';
export const ACCESS_CODE_HASH = '221e45e701886c3d9e5f12e5d7d0d2cb5ded7bbb785b1f1e26732c9d42369793';

export const defaultBusiness = {
  name: 'BREEZING PICTURES',
  tagline: 'Photography | Videography | Audio Coverage | Equipment Hire',
  phone: '099 374 1274',
  email: 'Breezingpix@gmail.com',
  website: 'Breezingpictures.com',
  location: 'Behind Petroda Filling Station, Mbayani, Blantyre',
  maps: 'https://g.page/breezing-pictures',
  bank: 'National Bank',
  account: '100-961-6531',
  airtel: '099 374 1274',
};

export const defaultLabels = {
  client: 'BILL TO',
  business: 'BUSINESS DETAILS',
  items: 'SERVICE BREAKDOWN',
  note: 'SERVICE NOTE',
  payment: 'PAYMENT DETAILS',
  total: 'TOTAL AMOUNT',
};

export const defaultSections = {
  intro: true,
  client: true,
  business: true,
  items: true,
  notes: true,
  payment: true,
  signature: true,
  footerBar: true,
};

export const defaultLayout = {
  dock: 'left',
  zoom: 'fit',
  compact: false,
};

export const sharedDocumentDefaults = {
  subtitle: '',
  dueDate: '',
  preparedBy: 'Breezing Pictures',
  clientPerson: '',
  clientPhone: '',
  clientEmail: '',
  extraCharge: 0,
  extraChargeLabel: 'Extra Charge',
  paidLabel: 'Amount Paid',
  softColor: '#f6f6f4',
  textColor: '#111111',
  lineColor: '#d9d5c8',
  fontScale: 1,
  pagePadding: 60,
  logoSrc: DEFAULT_LOGO_SRC,
  logoWidth: 260,
  logoMaxHeight: 112,
  logoAlign: 'center',
  signatureSrc: '',
  signatureWidth: 180,
  showSignature: false,
  watermarkSrc: DEFAULT_LOGO_SRC,
  watermarkWidth: 420,
  watermarkOpacity: 0.06,
  showWatermark: false,
};

export const templates = {
  invoice: {
    type: 'invoice',
    title: 'INVOICE',
    number: 'BP-2026-001',
    date: '2026-05-18',
    status: 'PENDING PAYMENT',
    currency: 'MK',
    clientName: 'Football Association of Malawi',
    clientAddress: 'Mpila House, Chiwembe, Limbe',
    eventName: 'Press Conference Coverage',
    venue: 'Mount Soche Hotel',
    intro: '',
    note: 'Professional photography coverage and on-site editing services provided by a team of 3. Edited pictures were delivered after the event.',
    terms: 'Thank you for choosing Breezing Pictures. We appreciate your trust and continued partnership.',
    paymentMethod: 'Bank Transfer / Airtel Money',
    reference: '',
    discount: 0,
    taxRate: 0,
    amountPaid: 0,
    accentColor: '#c9961a',
    darkColor: '#111111',
    paperColor: '#ffffff',
    labels: { ...defaultLabels, client: 'BILL TO', items: 'SERVICE BREAKDOWN' },
    items: [
      { category: 'Logistics', title: 'Transportation & Logistics', name: 'Transport', description: 'Transport and movement for the production team.', quantity: 1, unit: 'job', unitPrice: 50000, discount: 0, notes: '' },
      { category: 'Coverage', title: 'Photography Coverage', name: 'Team of 3 + Equipment', description: 'Photography coverage, editing, and delivery after the event.', quantity: 1, unit: 'job', unitPrice: 150000, discount: 0, notes: 'Includes on-site editing.' },
    ],
  },
  quotation: {
    type: 'quotation',
    title: 'EQUIPMENT HIRE QUOTATION',
    number: 'BP-Q-2026-001',
    date: '2026-05-21',
    status: 'VALID FOR EQUIPMENT HIRE',
    currency: 'MWK',
    clientName: 'Mpatamanga Hydro Power Limited',
    clientAddress: '',
    eventName: 'Equipment Hire',
    venue: 'Blantyre',
    intro: 'Thank you for your inquiry. Please find below our quotation for the requested equipment hire services.',
    note: 'We look forward to working with you. Thank you for choosing Breezing Pictures.',
    terms: 'Prepared By: BREEZING PICTURES',
    paymentMethod: 'Bank Transfer / Airtel Money',
    reference: '',
    discount: 0,
    taxRate: 0,
    amountPaid: 0,
    accentColor: '#b8872c',
    darkColor: '#0e2742',
    paperColor: '#ffffff',
    labels: { ...defaultLabels, client: 'QUOTED TO', items: 'EQUIPMENT DESCRIPTION' },
    items: [
      { category: 'Camera', title: 'Sony A6400 Camera', name: 'Camera Body', description: 'Mirrorless camera body for 4K production.', quantity: 1, unit: 'day', unitPrice: 80000, discount: 0, notes: '' },
      { category: 'Stabilizer', title: 'Gimbal Stabilizer', name: 'Gimbal', description: 'Stabilizer for smooth camera movement.', quantity: 1, unit: 'day', unitPrice: 50000, discount: 0, notes: '' },
      { category: 'Lenses', title: 'Two Camera Lenses', name: '16mm & 30mm', description: 'Two camera lenses for wide and normal coverage.', quantity: 1, unit: 'day', unitPrice: 100000, discount: 0, notes: '' },
      { category: 'Storage', title: '4K Memory Card', name: 'Memory Card', description: 'High-speed storage for 4K recording.', quantity: 1, unit: 'day', unitPrice: 50000, discount: 0, notes: '' },
    ],
  },
  inquiry: {
    type: 'inquiry',
    title: 'SERVICE INQUIRY',
    number: 'BP-I-2026-001',
    date: '2026-05-21',
    status: 'NEW INQUIRY',
    currency: 'MWK',
    clientName: 'Client Name',
    clientPerson: 'Contact Person',
    clientPhone: 'Phone number',
    clientEmail: 'Email address',
    clientAddress: 'Organization or address',
    eventName: 'Event / Project Name',
    venue: 'Venue or location',
    intro: 'Inquiry received for Breezing Pictures studio services.',
    note: 'Record client requirements, expected coverage time, delivery needs, and any special notes here.',
    terms: 'Prepared for internal studio follow-up.',
    paymentMethod: 'Not confirmed',
    reference: '',
    discount: 0,
    taxRate: 0,
    amountPaid: 0,
    accentColor: '#c9961a',
    darkColor: '#0e2742',
    paperColor: '#ffffff',
    labels: { ...defaultLabels, client: 'INQUIRY FROM', items: 'REQUESTED SERVICES' },
    items: [
      { category: 'Photography', title: 'Photography Coverage Inquiry', name: 'Coverage request', description: 'Client is asking for photography coverage details.', quantity: 1, unit: 'request', unitPrice: 0, discount: 0, notes: 'Confirm date, venue, number of hours, and delivery needs.' },
      { category: 'Video / Audio', title: 'Videography / Audio Requirements', name: 'Production request', description: 'Record requested video, audio, and editing requirements.', quantity: 1, unit: 'request', unitPrice: 0, discount: 0, notes: '' },
    ],
  },
  receipt: {
    type: 'receipt',
    title: 'RECEIPT',
    number: 'BP-R-2026-001',
    date: '2026-05-21',
    status: 'PAID',
    currency: 'MK',
    clientName: 'Client Name',
    clientAddress: '',
    eventName: 'Photography Coverage',
    venue: 'Blantyre',
    intro: 'Payment received with thanks.',
    note: 'This receipt confirms payment received for the services listed below.',
    terms: 'Authorized By: Breezing Pictures',
    paymentMethod: 'Airtel Money',
    reference: 'Receipt payment reference',
    discount: 0,
    taxRate: 0,
    amountPaid: 200000,
    accentColor: '#c9961a',
    darkColor: '#111111',
    paperColor: '#ffffff',
    labels: { ...defaultLabels, client: 'RECEIVED FROM', items: 'PAYMENT BREAKDOWN' },
    items: [
      { category: 'Coverage', title: 'Photography Coverage', name: 'Receipt Item', description: 'Photography coverage, editing, and delivery.', quantity: 1, unit: 'job', unitPrice: 200000, discount: 0, notes: '' },
    ],
  },
};
